### ISSUE TITLE
LotW output now includes an EOF tag

### ISSUE THREAD

**Issue by jasonhancock** [Matir/adifparser#4]
I used https://github.com/k0swe/lotw-qsl/blob/main/cmd/lotw-qsl/main.go to download a log of my LotW activity. A snippet of the end  of the file:

```
<CALL:5>K7WXB^M
<BAND:3>40M^M
<FREQ:7>7.07505^M
<MODE:3>FT8^M
<APP_LoTW_MODEGROUP:4>DATA^M
<QSO_DATE:8>20200901^M
<APP_LoTW_RXQSO:19>2020-10-21 04:59:04 // QSO record inserted/modified at LoTW^M
<TIME_ON:6>222600^M
<APP_LoTW_QSO_TIMESTAMP:20>2020-09-01T22:26:00Z // QSO Date & Time; ISO-8601^M
<QSL_RCVD:1>Y^M
<QSLRDATE:8>20201021^M
<APP_LoTW_RXQSL:19>2020-10-21 04:59:04 // QSL record matched/modified at LoTW^M
<DXCC:3>291^M
<COUNTRY:24>UNITED STATES OF AMERICA^M
<APP_LoTW_DXCC_ENTITY_STATUS:7>Current^M
<PFX:2>K7^M
<APP_LoTW_2xQSL:1>Y^M
<GRIDSQUARE:8>DN40DA49^M
<STATE:2>UT // Utah^M
<CNTY:7>UT,UTAH // Utah^M
<CQZ:2>03^M
<ITUZ:2>06^M
<eor>^M
^M
<APP_LoTW_EOF>^M
^M
```

I then tried to parse it, but it seems the `<APP_LoTW_EOF>` tag is causing an issue resulting in the error `Invalid field definition.`

**Comment by xylo04** [comment]
I've seen this as well. Considering this is non-conformant to ADIF, my workaround has been to [remove it before parsing](https://github.com/k0swe/kellog-func/blob/b638d6ae47765fb7c0bd41c38aa714dcfa5361a8/import_lotw.go#L93-L96).

**Comment by xylo04** [comment]
I've asked about this on the lotw-devel@reflector.arrl.org list. I'm advocating that they just remove the `<APP_LoTW_EOF>` tag; it's not valid ADIF and actually causes us more work to consume it.

**Comment by xylo04** [comment]
Per AA6YQ, this is apparently a long-standing wart on LotW's API and probably won't be removed despite the fact that it's nonstandard.

**Comment by Matir** [comment]
As far as I can tell, <APP_> fields are vendor-defined, but using one as a top-level record is new to me.  It seems there are two options:

1. Return a record specifically for this type and expect readers to consume it.
2. Special-handle this case and not return it.

I'm leaning towards the 2nd option to minimize the disruption to callers.

**Comment by jasonhancock** [comment]
I second option 2. I was hoping to have time to send in a PR for it, I just haven't gotten to it.

**Comment by xylo04** [comment]
Agreed with option 2 as well. It's basically [already done](https://github.com/Matir/adifparser/blob/4ff0e273b485ed789c8126759bd73327ec4d3430/lotwclient.go#L86-L91) in `lotwclient.go`, and just needs to be moved into `adifreader.go`.

**Comment by jasonhancock** [comment]
https://github.com/Matir/adifparser/pull/7 should address it
